
version: '3.3'


services:

  db:
    container_name: db-mysql
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: wpdb
        MYSQL_USER: wpuser
        MYSQL_PASSWORD: wppass
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wpuser
        WORDPRESS_DB_PASSWORD: wppass
        WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./src:/var/www/html/wp-content/plugins/meu-plugin
  
  adminer:
    container_name: adminer
    depends_on:
        - db
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  db: